---
title: "2020-06-22_HW10"
author: "Naeem Chowdhury"
date: "6/22/2020"
output: pdf_document
---

##1. Setup
### options
Set up global options
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy=TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=70))
knitr::opts_chunk$set(fig.height=4, fig.width=6)
```

### libraries
Load in needed libraries 
```{r, include=FALSE}
library(tidyverse)
# library(RColorBrewer)
library(ggplot2)
# library(haven)
# library(plotly)
#install.packages('rgl')
# library(rgl)
# library(ISLR)
# install.packages('cowplot')
library(cowplot)
```

## 2. File management
### Create variables for directories
```{r file_management, include=FALSE}
project.dir <- getwd() #naeem
output.dir <- "/Output"
data.dir <- "C:/Users/Naeem Cho/Desktop/School Work/Data_Viz/Datasets"
setwd(project.dir)
getwd()
```

## 3. Importing Data
```{r, echo = FALSE, include=FALSE}
default <- read_csv(file.path(data.dir, "Default.csv"))
```

# Part a.

```{r}
# Transform all the Yes and No string values into booleans
default.df <- default %>%
  mutate(default1 = ifelse(default == "Yes",TRUE, FALSE)) %>%
  select(default1, balance)
```


```{r}
# Fitting the logistic regression

fit1 <- glm(default1 ~ balance, family = binomial(link = logit), data = default.df)

summary(fit1)
```

```{r}
## increase in odds for 100 dollar increase in balance
exp(0.5499)
```

```{r}
# Confidence interval:
exp(confint(fit1))
```

__Interpretation:__

The odds of defaulting on a loan are predicted to increase 1.7 fold for every 100 dollar increase in loan balance.


## Part b.

```{r}
# sequence of balances
balance.new <- seq(0, max(default.df$balance1) + 1000, 1)


# Creating data to plot
plotdata <- tibble(
  balance = balance.new,
  log.odds = predict(fit1,newdata = data.frame(balance = balance.new), type = "link"),
  odds = exp(log.odds),
  prob = odds/(1+odds)
)

predictions <- predict(fit1, newdata = data.frame(balance = balance.new), type = "link", se.fit = TRUE)

predictions$se.fit

```

```{r}
# Plotting the probability curve
plot.probs <- ggplot(plotdata, 
                     aes(x = balance, y = prob)) +
  geom_line(color = "blue", size = 1) +
  geom_ribbon(aes(ymin = prob.LB, ymax = prob.UB))
  theme_bw()

plot.probs
```



